# Generated by Django 4.0.6 on 2024-08-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordsdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontConveyorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('80', '80'), ('100', '100'), ('120', '120')], max_length=10)),
                ('model', models.CharField(choices=[('model_a', 'Model A'), ('model_b', 'Model B'), ('model_c', 'Model C')], max_length=10)),
                ('specification', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('quality', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RearConveyorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('80', '80'), ('100', '100'), ('120', '120')], max_length=10)),
                ('model', models.CharField(choices=[('model_a', 'Model A'), ('model_b', 'Model B'), ('model_c', 'Model C')], max_length=10)),
                ('specification', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=255)),
                ('quality', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
